### ISSUE TITLE
Meeting point

### ISSUE THREAD

**Issue by gortazar** [jcfernandezrebollo/jenkins-flame-graphs#1]
Si ves este issue en la web de zube.io es que estamos viendo el mismo proyecto. Contesta con un comentario para saberlo.

**Comment by jcfernandezrebollo** [comment]
Todo correcto!

**Comment by gortazar** [comment]
Ok. Algunas cuestiones primero:
- ¿Estás familiarizado con git?
- ¿Entiendes o intuyes cómo funciona zube.io desde el punto de vista de la planificación del proyecto?

**Comment by jcfernandezrebollo** [comment]
Nunca he usado Git, pero más o menos creo que voy entendiendo como va; y en cuanto a lo de la planificación de proyectos he usado trello, que supongo que sera similar a zube.

**Comment by gortazar** [comment]
Sí, es muy similar. En esta semana iré planificando cosas. Cualquier duda la vamos comentando en el issue correspondiente.
